symbols = [                                                                                                                                                                                                                                                                                                                                                 
  "^BTC-PERPETUAL$"
#  "^BTC-[0-9]{1,2}[A-Z]{3}[0-9]{2}$",  # futures                                                                           
#  "^ETH-[0-9]{1,2}[A-Z]{3}[0-9]{2}$",  # futures                                                                           
#  "^BTC(_USD[A-Z]?)?-PERPETUAL$",      # swaps                                                                          
#  "^ETH(_USD[A-Z]?)?-PERPETUAL$",      # swaps                                                                          
]
