[symbols]
  regex="USD.*"  # optional, used to subscribe funds

  [symbols.bitmex]
  regex=["XBTUSD", "XBT.*"]

  [symbols.deribit]
  regex=".*"

  [symbols.ftx]
  regex=".*"


[users]

  [users.MD1]
  component="roq-fix-client-test"
  username="tbmd1"

  [users.MD2]
  component="roq-fix-client-test"
  username="tbmd2"

  [users.OM1]
  component="roq-fix-client-test"
  username="tbom1"
  password="secret"
  account="A1"

  [users.OM2]
  component="roq-fix-client-test"
  username="tbom2"
  password="secret"
  account="A2"


# override default mappings?

#[statistics]
#
#  [statistics.FUNDING_RATE]
#  fix_md_entry_type="SETTLEMENT_PRICE"
